<a href="https://colab.research.google.com/github/Emyfoton/MetodosI_EmilyCastillo_SebastianRodriguez/blob/main/Tarea_%C3%81lgebra_Lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

En Python, implemente una clase para solucionar sistemas lineales. El constructor de clase deber recibir la matriz y el vector independiente. El primer método de clase resuelve el sistema usando el método de Jacobi, y el segundo método resuelve el sistema usando el método de Gaus-Seidel. En la pantalla debe aparecer el número de iteraciones necesarias para resolver el problema.


In [ ]:
#Punto 2

import numpy as np

G0=(lambda x,y,z: 3*x - y - z - 1., \
    lambda x,y,z: -x + 3*y + z - 3., \
    lambda x,y,z: 2*x + y + 4*z - 7.)

A=np.array([[3,-1,-1],[-1,3,1],[2,1,4]])
b=np.array([1,3,7])

def gauss_seidel(A, b, x0, tol=1e-6, max_iter=100000):

   x = x0.copy()

   for it in range(max_iter):

    x_n = np.copy(x)

    for i in range(A.shape[0]):
      Suma = 0.
      for j in range(A.shape[1]):
        if i != j:
          Suma += A[i,j]*x_n[j]

          x_n[i] = (b[i] - Suma)/A[i,i]

    print(x_n)

    if np.linalg.norm((A@x_n)-b) < tol:
      break

    x = np.copy(x_n)


   return x_n, it

In [ ]:
gauss_seidel(A,b,np.array([10,37,58]))

[ 32  -7 -12]
[-6  3  4]
[2 0 0]
[0 1 1]
[1 1 1]


(array([1, 1, 1]), 4)

In [ ]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [ ]:
#Punto 3
import numpy as np

class Robot:
    def __init__(self, matriz, vector):
        self.matriz = np.array(matriz)
        self.vector = np.array(vector)

    def metodo_jacobi(self, max_iter=1000):
        n = len(self.vector)
        x = np.zeros(n)
        iteraciones = 0

        for iteraciones in range(max_iter):
            x_nuevo = np.copy(x)
            for i in range(n):
                suma = sum(self.matriz[i][j] * x[j] for j in range(n) if j != i)
                x_nuevo[i] = (self.vector[i] - suma) / self.matriz[i][i]

            if np.allclose(x, x_nuevo, atol=1e-10):
                break

            x = x_nuevo
        print(f"Jacobi convergió en {iteraciones + 1} iteraciones")
        return x

    def metodo_gauss_seidel(self, max_iter=1000):
        n = len(self.vector)
        x = np.zeros(n)
        iteraciones = 0

        for iteraciones in range(max_iter):
            x_anterior = np.copy(x)

            for i in range(n):
                suma = sum(self.matriz[i][j] * x[j] for j in range(n) if j != i)
                x[i] = (self.vector[i] - suma) / self.matriz[i][i]

            if np.allclose(x, x_anterior, atol=1e-10):
                break

        print(f"Gauss-Seidel convergió en {iteraciones + 1} iteraciones")
        return x

matriz = [[4, -1, 0, 0],
          [-1, 4, -1, 0],
          [0, -1, 4, -1],
          [0, 0, -1, 3]]

vector = [15, 10, 10, 10]

robot = Robot(matriz, vector)
solucion_jacobi = robot.metodo_jacobi()
solucion_gauss_seidel = robot.metodo_gauss_seidel()

print(f"Solución por Jacobi: {solucion_jacobi}")
print(f"Solución por Gauss-Seidel: {solucion_gauss_seidel}")



Jacobi convergió en 14 iteraciones
Gauss-Seidel convergió en 9 iteraciones
Solución por Jacobi: [4.99995622 4.99992395 4.9999182  4.99993395]
Solución por Gauss-Seidel: [4.99999542 4.99999671 4.99999847 4.99999949]


In [ ]:
# Punto 4



matriz1=np.array([[1,0,0],[5,1,0],[-2,3,1]])
matriz2=np.array([[4,-2,1],[0,3,7],[0,0,2]])


def multiplicar_matrices(matriz1, matriz2):
  n=len(matriz1)
  m=len(matriz2[0])
  p=len(matriz2)
  x=np.zeros((n,m))
  if n!=m:
    print("No se puede multiplicar")
  else:
    for i in range(n):
      for j in range(m):
        for k in range(p):
         x[i][j] += matriz1[i][k] * matriz2[k][j]
  return x

In [ ]:
# Punto 8

matriz=np.array([[4,-2,1],[20,-7,12],[-8,13,17]])

def LU(matriz):
  L=np.zeros_like(matriz)
  for i in range(len(L)):
    for j in range(len(L[0])):
      if i==j:
        L[i][j]=1

  U = matriz.astype(np.float64)
  n = U.shape[0]

  for k in range(n):
      for w in range(k+1,n):
          u = U[w,k]/U[k,k]
          L[w,k]=u
          U[w,:] -= u*U[k,:]

  return L,U

In [ ]:
LU(matriz)

(array([[ 1,  0,  0],
        [ 5,  1,  0],
        [-2,  3,  1]]),
 array([[ 4., -2.,  1.],
        [ 0.,  3.,  7.],
        [ 0.,  0., -2.]]))

In [ ]:
#Punto 9

A=np.array([[3, -1, -1],
           [-1, 3, -1],
           [-1, -1, 3]])
B= np.array([1, 3, 7])


In [ ]:
# Punto 13

def Jacobian_4(f,r,h=0.01):

  n = r.shape[0]

  J = np.zeros((n,n))

  for i in range(n):
    for j in range(n):

      d_rf = r.copy()
      d_rb = r.copy()
      rf = r.copy()
      rb = r.copy()

      d_rf[j] = d_rf[j] + 2*h
      rf[j] = rf[j] + h
      rb[j] = rb[j] - h
      d_rb[j] = d_rb[j] - 2*h

      J[i,j] = (-f[i](d_rf[0],d_rf[1],d_rf[2]) + 8*f[i](rf[0],rf[1],rf[2]) - 8*f[i](rb[0],rb[1],rb[2]) + f[i](d_rb[0],d_rb[1],d_rb[2]))/(12*h)

  return J

In [ ]:
Jacobian_4(F2,np.array([0.5,0.5,0.5]))

array([[ 6.        ,  0.24740396,  0.24740396],
       [ 0.37377753,  9.        ,  0.32802064],
       [-1.16820117, -1.16820117, 60.        ]])

In [ ]:
GetJacobian2(F2,np.array([0.5,0.5,0.5]))

array([[ 6.        ,  0.24740396,  0.24740396],
       [ 0.37377753,  9.        ,  0.32802064],
       [-1.16820118, -1.16820118, 60.        ]])